# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup tModLoader
      run:
        cd ..
        mkdir tModLoader
        cd tModLoader
        wget https://github.com/tModLoader/tModLoader/releases/download/v2025.03.3.1/tModLoader.zip
        unzip tModLoader.zip
    - name: Setup tml env
      run:
        cd ..
        echo "<Project ToolsVersion=\"14.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
          <Import Project=\"$(pwd)\tMLMod.targets" />
        </Project>" > tModLoader.targets
    - name: Build
      run:
        dotnet build --no-restore

